### PR TITLE
A few fixes and enhancements for the order writer and reader

### PR DESCRIPTION
**Pull request by jmu-horaios**
Hi there,
I stumpled upon your OpenTrans.net package and was very pleased to see, that there is already something out there to tackle the OpenTrans standard. It works super well! There are just a few missing pieces to match my current needs, so I worked on that.

Maybe you can have a look. It would be nice to hear from you or to see a merge ;D
Thanks for your good work!

### CODE REVIEW

**Comment by stephanstapel** [comment]
How about adding a constructor to the remark class with a mandatory Value parameter? This would make clear that it necessary to fill this field

**Comment by jmu-horaios** [comment]
Good point, but I could not find any other class where mandatory parameters are handled like this. I think it would be more consistent to leave it as it is. The Product ID for an ORDER_ITEM for example does also not have a constructor.

Or did I get you wrong?

**Comment by stephanstapel** [comment]
Hi Jan,
yes, you are right. But maybe this is a good point to start.
You might have seen my other projects, especially https://github.com/stephanstapel/ZUGFeRD-csharp. There are lots of discussions where people want a slicker xml mapping but I'm somewhat again just providing a c#-to-xml mapping.

**Comment by jmu-horaios** [comment]
Hi Stephan,
you are also right. This would be much cleaner. I pushed a version to my fork. If you like you can have a look at it.
Maybe it already suits your taste. If so, I'll create a pull request.
[https://github.com/jmu-horaios/OpenTrans.net/blob/development/OpenTrans.net/Remark.cs](https://github.com/jmu-horaios/OpenTrans.net/blob/development/OpenTrans.net/Remark.cs)

**Comment by stephanstapel** [comment]
Looks good. Are there other places where this change would make sense? The OrderItem constructor would like quite awkward when you need to pass a productId instance though. What do you think?

**Comment by jmu-horaios** [comment]
Hi Stephan,

I am not sure if it makes sense to apply this change only partially. I would suggest to use it on every OpenTrans-Element, which has mandatory values. This however can and will get quite awkward, especially with elements which have multiple mandatory values. On one hand, this would make it more easy to create valid documents, on the other hand, we would loose flexibility and get more awkward code. Maybe we should stick with the current approach, but instead of forcing users to the standard, we could give them better hints on what is mandatory or optional - to the official guidelines - with comments.
Maybe there are implementations out there which are intended to not stick 100% to the standard, but still want to be used that way. I really do not know whats best at this point 😬

**Comment by jmu-horaios** [comment]
Here is an example, of how it could look like:
[https://github.com/jmu-horaios/OpenTrans.net/blob/development2/OpenTrans.net/Remark.cs](https://github.com/jmu-horaios/OpenTrans.net/blob/development2/OpenTrans.net/Remark.cs)

At the start of the summary for each attribute, we could just pop a [Mandatory/Optional] flag to indicate the significance.
Could this be a solution?

**Comment by stephanstapel** [comment]
The idea is good. I just fear that this won't be pervasive all over the code since it is no IDE feature to pay attention to this tag. Let's leave it like it was.

**Comment by jmu-horaios** [comment]
Yep, there is not IDE feature to highlight this, but it would still be an easy access this info. Else you would have to fire up the PDF or some other source. I would have no problem going through the code to add the 'tags'.

Or did you mean by 'like it was' the constructor-variant?

**Pull request merged**
